services:
  proxy-gateway:
    build:
      context: ./proxy-gateway
    container_name: proxy-gateway
    ports:
      - 3333:3333
    networks:
      - microservices

  db-products:
    image: mysql:8.0-debian
    container_name: db-products
    environment:
      - MYSQL_DATABASE=db-products
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - microservices

  api-products:
    image: node:22
    entrypoint: tail -f /dev/null
    container_name: api-products
    volumes:
      - ./products:/app
    networks:
      - microservices

  db-users:
    image: mysql:8.0-debian
    container_name: db-users
    environment:
      - MYSQL_DATABASE=db-users
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - microservices

  api-users:
    image: node:22
    entrypoint: tail -f /dev/null
    container_name: api-users
    volumes:
      - ./users:/app
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
