services:
  db:
    image: mysql:8.0-debian
    container_name: db-purchases
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=purchases
      - MYSQL_ROOT_PASSWORD=root

networks:
  microservices:
    driver: bridge
