services:
  db:
    image: mysql:8.0-debian
    container_name: db-products
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_ROOT_PASSWORD=root

networks:
  microservices:
    driver: bridge
