services:
  db:
    image: mysql:8.0-debian
    container_name: db-users
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root

networks:
  microservices:
    driver: bridge
